(()=>{
  'use strict';
    const {CURRENT_YEAR,NISA_START,NISA_ANNUAL_LIMIT,NISA_LIFETIME_LIMIT,UNIVERSITY_AWAY_ANNUAL,stageNames,stageShort,presets,educationCosts,examCram}=window.EducationAssumptions;
    const clone=v=>JSON.parse(JSON.stringify(v));
    const ym=v=>{let m=/^(\d{4})-(\d{2})(?:-(\d{2}))?$/.exec(String(v||''));if(!m)return null;let value={y:+m[1],m:+m[2],d:m[3]?+m[3]:1};return value.m>=1&&value.m<=12&&value.d>=1&&value.d<=new Date(value.y,value.m,0).getDate()?value:null};
    const monthCode=(y,m)=>y*12+m;
    const codeYear=code=>Math.floor((code-1)/12),codeMonth=code=>code-codeYear(code)*12;
    const normalizeText=v=>String(v??'').trim().replace(/[０-９]/g,c=>String.fromCharCode(c.charCodeAt(0)-0xFEE0)).replace(/[，、]/g,',').replace(/[．。]/g,'.').replace(/[－ー]/g,'-');
    const numberOrNull=v=>{let text=normalizeText(v).replace(/,/g,'');if(text==='')return null;let n=Number(text);return Number.isFinite(n)?n:null};
    const manOrNull=v=>{let n=numberOrNull(v);return n===null?null:Math.round(n*10000)};
    const emptyPlan=()=>({base:15000,periods:[]});
    function createChild(birth='2023-12-01',name='お子さま'){return {name,birth,preparedCash:0,existingInvestmentValue:0,paths:{el:'public',j:'public',h:'public',u:'national',home:'home',years:4},examModes:{middle:false,high:false,university:false},overrides:{},investment:emptyPlan()}}
    function defaults(){return {version:8,page:'dashboard',edChild:0,resultChild:'all',setupComplete:false,setupStep:0,common:{start:'2027-01',rate:3,inflation:2,preparedCash:0,withdraw:'university',nisaMode:'free',nisaCashFallback:true},benefits:{childAllowance:true,allocation:100,highSupport:true,highPublic:118800,highPrivate:457200,universitySupport:false,additionalEligibleSiblings:0,manualAnnual:0,manualStart:2030,manualEnd:2030},children:[createChild('','お子さま 1')]}}
    function normalizeBirth(value){let text=String(value||'');if(text==='')return '';if(/^\d{4}-\d{2}-\d{2}$/.test(text))return text;if(/^\d{4}-\d{2}$/.test(text))return `${text}-${text.endsWith('-04')?'02':'01'}`;return '2023-12-01'}
    function migrate(raw){let base=defaults();if(!raw||!Array.isArray(raw.children)||!raw.children.length)return base;let model=clone(base);model.page='dashboard';model.edChild=Math.max(0,Math.min(+raw.edChild||0,raw.children.length-1));model.setupComplete=raw.setupComplete===undefined?true:!!raw.setupComplete;model.setupStep=Math.max(0,Math.min(2,+raw.setupStep||0));Object.assign(model.common,raw.common||{});delete model.common.preset;Object.assign(model.benefits,raw.benefits||{});model.children=raw.children.slice(0,10).map((source,i)=>{let child=createChild(normalizeBirth(source.birth),source.name||`お子さま ${i+1}`);Object.assign(child,source);child.birth=normalizeBirth(source.birth);delete child.elementaryStart;delete child.universityStart;delete child.existingInvestmentCost;delete child.extras;child.paths=Object.assign(createChild().paths,source.paths||{});child.examModes=Object.assign(createChild().examModes,source.examModes||{});child.investment=Object.assign(emptyPlan(),source.investment||{});child.investment.periods=(Array.isArray(child.investment.periods)?child.investment.periods:[]).filter(period=>period&&['start','end','monthly'].some(key=>normalizeText(period[key])!==''));child.overrides=source.overrides&&typeof source.overrides==='object'?source.overrides:{};return child});model.resultChild=raw.resultChild==='all'||Number.isInteger(+raw.resultChild)&&+raw.resultChild>=0&&+raw.resultChild<model.children.length?raw.resultChild==='all'?'all':+raw.resultChild:'all';model.version=8;return model}
    function elementaryYear(c){let birth=ym(c.birth);if(!birth)return CURRENT_YEAR+6;return birth.y+(birth.m<4||(birth.m===4&&birth.d===1)?6:7)}
    function universityYear(c){return elementaryYear(c)+12}
    function ageInMonth(c,code){let birth=ym(c.birth);return birth?Math.floor((code-monthCode(birth.y,birth.m))/12):0}
    function stageLabel(record){return `${stageNames[record.stage]}${record.grade}年`}
    function stageShortLabel(record){return `${stageShort[record.stage]}${record.grade}`}
    function matchingPreset(paths){return Object.entries(presets).find(([,preset])=>['el','j','h'].every(stage=>paths?.[stage]===preset.paths[stage]))?.[0]||null}
    function cramFor(c,stage,grade,cost){let amount=cost.cram[Math.min(grade-1,cost.cram.length-1)]||0;for(const [mode,setting] of Object.entries(examCram)){if(c.examModes?.[mode]&&setting.stage===stage&&setting.grades[grade]!==undefined)return setting.grades[grade]}return amount}
    function schoolRecords(model,c,index){let start=elementaryYear(c),university=universityYear(c),stages=[['el',6,start],['j',3,start+6],['h',3,start+9],['u',+c.paths.years,university]],records=[];for(const [stage,count,firstYear] of stages){for(let offset=0;offset<count;offset++){let year=firstYear+offset,grade=offset+1,key=`${stage}${offset}`,override=c.overrides?.[key]||{},factor=Math.pow(1+(+model.common.inflation||0)/100,Math.max(0,year-CURRENT_YEAR)),cost=educationCosts[stage][c.paths[stage]],base={year,stage,grade,key,child:index,tuition:cost.annual,entry:offset===0?cost.entry:0,cram:cramFor(c,stage,grade,cost),lesson:cost.lesson,other:cost.other+(stage==='u'&&c.paths.home==='away'?UNIVERSITY_AWAY_ANNUAL:0)};for(const kind of ['tuition','entry','cram','lesson','other'])base[kind]=override[kind]===undefined?Math.round(base[kind]*factor):+override[kind];records.push(base)}}return records}
    function supportCount(model,year){return model.children.filter(c=>year<=universityYear(c)+(+c.paths.years||4)-1).length+(+model.benefits.additionalEligibleSiblings||0)}
    function discountFor(model,record){let benefit=model.benefits,tuitionDiscount=0,entryDiscount=0;if(benefit.highSupport&&record.stage==='h')tuitionDiscount=Math.min(record.tuition,record.child!==undefined&&model.children[record.child].paths.h==='public'?+benefit.highPublic:+benefit.highPrivate);if(benefit.universitySupport&&record.stage==='u'&&supportCount(model,record.year)>=3){let privateU=model.children[record.child].paths.u.startsWith('private'),tuitionCap=privateU?700000:535800,entryCap=privateU?260000:282000;tuitionDiscount+=Math.min(Math.max(0,record.tuition-tuitionDiscount),tuitionCap);entryDiscount=Math.min(record.entry,entryCap)}return {tuitionDiscount,entryDiscount,total:tuitionDiscount+entryDiscount}}
    function allowanceForMonth(model,c,index,code){if(!model.benefits.childAllowance)return 0;let birth=ym(c.birth),year=codeYear(code),month=codeMonth(code);if(!birth||code<monthCode(birth.y,birth.m)||code>monthCode(birth.y+19,3))return 0;let older=[...model.children].sort((a,b)=>String(a.birth).localeCompare(String(b.birth))).findIndex(x=>x===c)+1+(+model.benefits.additionalEligibleSiblings||0),ageMonths=code-monthCode(birth.y,birth.m),base=ageMonths<36?15000:older>=3?30000:10000;return Math.round(base*Math.max(0,Math.min(100,+model.benefits.allocation||0))/100)}
    function periods(plan){let list=Array.isArray(plan.periods)?plan.periods:[];return list.map(p=>({start:+p.start,end:+p.end,monthly:+p.monthly})).filter(p=>p.start>=1&&p.end>=p.start&&p.monthly>=0)}
    function planAmount(plan,yearNo){let period=periods(plan).find(p=>yearNo>=p.start&&yearNo<=p.end);return period?period.monthly:+plan.base||0}
    function allowedWithdrawal(model,c,code){return model.common.nisaMode!=='nisa'||ageInMonth(c,code)>=12}
    function eligibleNisa(c,code){let year=codeYear(code);return year>=NISA_START&&ageInMonth(c,code)>=0&&ageInMonth(c,code)<18}
    function validMonth(value){return /^\d{4}-(0[1-9]|1[0-2])$/.test(String(value||''))}
    function validDate(value){let date=ym(value);return !!date&&/^\d{4}-\d{2}-\d{2}$/.test(String(value||''))}
    function shouldUseAssets(model,stage){return model.common.withdraw==='all'||(model.common.withdraw==='high'&&(stage==='h'||stage==='u'))||(model.common.withdraw==='university'&&stage==='u')}
    function calculate(model){let children=model.children,records=children.flatMap((c,i)=>schoolRecords(model,c,i).map(r=>Object.assign(r,{discount:discountFor(model,r)}))),first=monthCode(CURRENT_YEAR,1),last=Math.max(...records.map(r=>monthCode(r.year+1,3))),annual=new Map(),funds=children.map(c=>({cash:+c.preparedCash||0,invest:+c.existingInvestmentValue||0,nisaLifetime:0,nisaYear:0,nisaYearValue:null,contribution:0,benefit:0,withdrawal:0,shortage:0,blocked:0,universityBefore:null}));
      function annualFor(year){if(!annual.has(year))annual.set(year,{year,tuition:0,entry:0,cram:0,lesson:0,other:0,gross:0,directDiscount:0,benefitCash:0,householdDirect:0,contribution:0,withdrawal:0,shortage:0,nisaBlocked:0,balance:0,children:children.map(()=>({gross:0,directDiscount:0,benefitCash:0,householdDirect:0,withdrawal:0,shortage:0,contribution:0,balance:0}))});return annual.get(year)}
      for(let y=CURRENT_YEAR;y<=codeYear(last);y++)annualFor(y);let events=new Map();function addEvent(code,event){if(!events.has(code))events.set(code,[]);events.get(code).push(event)}
      for(const r of records){let a=annualFor(r.year),netTuition=Math.max(0,r.tuition-r.discount.tuitionDiscount),netEntry=Math.max(0,r.entry-r.discount.entryDiscount),extras=r.cram+r.lesson+r.other,total=r.tuition+r.entry+extras;a.tuition+=r.tuition;a.entry+=r.entry;a.cram+=r.cram;a.lesson+=r.lesson;a.other+=r.other;a.gross+=total;a.directDiscount+=r.discount.total;a.children[r.child].gross+=total;a.children[r.child].directDiscount+=r.discount.total;if(netEntry)addEvent(monthCode(r.year,3),{child:r.child,stage:r.stage,amount:netEntry,type:'入学準備費'});if(netTuition)addEvent(monthCode(r.year,4),{child:r.child,stage:r.stage,amount:netTuition,type:'年間学校費'});for(let p=0;p<12;p++){let date=monthCode(r.year,4)+p,amount=extras/12;if(amount)addEvent(date,{child:r.child,stage:r.stage,amount,type:'学校外費用'})}}
      let start=ym(model.common.start)||{y:CURRENT_YEAR,m:1},startCode=monthCode(start.y,start.m),sharedCash=+model.common.preparedCash||0,firstShortage=null;
      for(let code=first;code<=last;code++){let year=codeYear(code),month=codeMonth(code),a=annualFor(year),monthlyRate=(+model.common.rate||0)/1200;for(const fund of funds)fund.invest*=1+monthlyRate;
        children.forEach((c,i)=>{let fund=funds[i],univCode=monthCode(universityYear(c),4);if(code===monthCode(universityYear(c),3))fund.universityBefore=fund.cash+fund.invest;if(code>=startCode&&code<univCode){let wanted=Math.max(0,planAmount(c.investment,Math.floor((code-startCode)/12)+1)),accepted=wanted;if(model.common.nisaMode==='nisa'){if(fund.nisaYearValue!==year){fund.nisaYearValue=year;fund.nisaYear=0}if(!eligibleNisa(c,code))accepted=0;else accepted=Math.min(wanted,Math.max(0,NISA_ANNUAL_LIMIT-fund.nisaYear),Math.max(0,NISA_LIFETIME_LIMIT-fund.nisaLifetime));fund.nisaYear+=accepted;fund.nisaLifetime+=accepted}fund.invest+=accepted;fund.contribution+=accepted;a.contribution+=accepted;a.children[i].contribution+=accepted;let overflow=wanted-accepted;if(overflow>0){fund.blocked+=overflow;a.nisaBlocked+=overflow;if(model.common.nisaCashFallback){fund.cash+=overflow;fund.contribution+=overflow;a.contribution+=overflow;a.children[i].contribution+=overflow}}}
          let allowance=allowanceForMonth(model,c,i,code);if(allowance){fund.cash+=allowance;fund.benefit+=allowance;a.benefitCash+=allowance;a.children[i].benefitCash+=allowance}});
        if(year>=+model.benefits.manualStart&&year<=+model.benefits.manualEnd&&+model.benefits.manualAnnual>0){let amount=(+model.benefits.manualAnnual)/12;sharedCash+=amount;a.benefitCash+=amount}
        for(const event of events.get(code)||[]){let fund=funds[event.child],child=children[event.child],remaining=event.amount,childAnnual=a.children[event.child];if(!shouldUseAssets(model,event.stage)){a.householdDirect+=remaining;childAnnual.householdDirect+=remaining;continue}let cashPaid=Math.min(fund.cash,remaining);fund.cash-=cashPaid;remaining-=cashPaid;let investPaid=0;if(remaining>0&&allowedWithdrawal(model,child,code)){investPaid=Math.min(fund.invest,remaining);fund.invest-=investPaid;remaining-=investPaid}let sharedPaid=Math.min(sharedCash,remaining);sharedCash-=sharedPaid;remaining-=sharedPaid;let paid=cashPaid+investPaid+sharedPaid;fund.withdrawal+=paid;a.withdrawal+=paid;childAnnual.withdrawal+=paid;if(remaining>0){fund.shortage+=remaining;a.shortage+=remaining;childAnnual.shortage+=remaining;if(!firstShortage)firstShortage={year,month,child:event.child,stage:event.stage,amount:remaining,type:event.type}}}
        if(month===12||code===last){let totalBalance=sharedCash;funds.forEach((fund,i)=>{let balance=fund.cash+fund.invest;annualFor(year).children[i].balance=balance;totalBalance+=balance});a.balance=totalBalance}}
      let annualRows=[...annual.values()].sort((a,b)=>a.year-b.year);let totals={gross:annualRows.reduce((n,a)=>n+a.gross,0),directDiscount:annualRows.reduce((n,a)=>n+a.directDiscount,0),benefitCash:annualRows.reduce((n,a)=>n+a.benefitCash,0),householdDirect:annualRows.reduce((n,a)=>n+a.householdDirect,0),contribution:annualRows.reduce((n,a)=>n+a.contribution,0),withdrawal:annualRows.reduce((n,a)=>n+a.withdrawal,0),shortage:annualRows.reduce((n,a)=>n+a.shortage,0),nisaBlocked:annualRows.reduce((n,a)=>n+a.nisaBlocked,0),balance:annualRows.at(-1)?.balance||0,sharedCash};return {records,annual:annualRows,funds,totals,firstShortage}}
    function requiredMonthly(model,index){let trial=clone(model);trial.children=[clone(model.children[index])];trial.edChild=0;trial.common.withdraw='all';trial.common.preparedCash=index===0?+model.common.preparedCash||0:0;trial.children[0].investment.periods=[];let high=500000,cap=clone(trial);cap.children[0].investment={base:high,periods:[]};if(calculate(cap).totals.shortage>0)return null;let lo=0,hi=high/1000;while(lo<hi){let mid=Math.floor((lo+hi)/2),probe=clone(trial);probe.children[0].investment={base:mid*1000,periods:[]};if(calculate(probe).totals.shortage>0)lo=mid+1;else hi=mid}return lo*1000}
    function validateModel(model){let errors={};if(!validMonth(model.common.start))errors['common.start']='積立開始月を選択してください。';if(!Number.isFinite(+model.common.rate)||+model.common.rate<0||+model.common.rate>15)errors['common.rate']='年利は0〜15％で入力してください。';if(!Number.isFinite(+model.common.inflation)||+model.common.inflation<0||+model.common.inflation>10)errors['common.inflation']='上昇率は0〜10％で入力してください。';if(!Number.isFinite(+model.common.preparedCash)||+model.common.preparedCash<0)errors['common.preparedCash']='0以上の金額を入力してください。';if(!Array.isArray(model.children)||model.children.length<1||model.children.length>10)errors.children='お子さまは1〜10人で設定してください。';(model.children||[]).forEach((c,i)=>{let prefix=`children.${i}`;if(!String(c.name||'').trim())errors[`${prefix}.name`]='名前を入力してください。';if(!validDate(c.birth))errors[`${prefix}.birth`]='生年月日を選択してください。';if(!Number.isFinite(+c.preparedCash)||+c.preparedCash<0)errors[`${prefix}.preparedCash`]='0以上の金額を入力してください。';if(!Number.isFinite(+c.existingInvestmentValue)||+c.existingInvestmentValue<0)errors[`${prefix}.existingInvestmentValue`]='0以上の金額を入力してください。';if(!Number.isFinite(+c.investment.base)||+c.investment.base<0||+c.investment.base>1000000)errors[`${prefix}.investment.base`]='月額は0〜100万円で入力してください。';let used=[];for(const p of c.investment.periods||[]){if(!Number.isInteger(+p.start)||!Number.isInteger(+p.end)||+p.start<1||+p.end<+p.start||!Number.isFinite(+p.monthly)||+p.monthly<0){errors[`${prefix}.investment.periods`]='開始・終了・金額を確認してください。';continue}let normalized={start:+p.start,end:+p.end};if(used.some(x=>normalized.start<=x.end&&x.start<=normalized.end))errors[`${prefix}.investment.periods`]='期間が重複しています。';used.push(normalized)}});return errors}
    function schoolStatus(model,c,year){let record=schoolRecords(model,c,0).find(r=>r.year===year);if(record)return stageShortLabel(record);return year<elementaryYear(c)?'未就学':'卒業後'}
    window.EducationSimulator={clone,ym,monthCode,codeYear,codeMonth,normalizeText,numberOrNull,manOrNull,emptyPlan,createChild,defaults,normalizeBirth,migrate,elementaryYear,universityYear,ageInMonth,stageLabel,stageShortLabel,matchingPreset,cramFor,schoolRecords,supportCount,discountFor,allowanceForMonth,periods,planAmount,allowedWithdrawal,eligibleNisa,validMonth,validDate,shouldUseAssets,calculate,requiredMonthly,validateModel,schoolStatus};
  })();
